export const EVENT_INFO_ITEMS_SETUP_SQL = `-- Extra event facts (title + description) for the app and the bot.
-- Do not touch guest_profiles or conversation_messages.

create table if not exists public.event_info_items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.event_info_items enable row level security;

comment on table public.event_info_items is
  'Extra event facts (title + description) shared by the admin, mobile app, and concierge bot.';
`;
